[package]
name = "knock-knock"
version = "0.2.0"
authors = ["Sunshine <sunshine@uberspace.net>"]
description = "CLI tool for obtaining internet domain information"
homepage = "https://github.com/snshn/knock-knock"
repository = "https://github.com/snshn/knock-knock"
edition = "2018"
license = "CC0-1.0"

[dependencies]
chrono = "0.4.19"
whois-rust = "1.3.3"
whoisthere = "0.1.2"

[dependencies.clap]
version = "2.33.3"
default-features = false
features = [ "suggestions" ]
